### ISSUE TITLE
Add Instructions for updating the Robot Controller version for Android Studio users.

### ISSUE THREAD

**Issue by Lunerwalker2** [FIRST-Tech-Challenge/ftcdocs#159]
The current page for updating the RC app (https://ftc-docs.firstinspires.org/ftc_sdk/updating/rc_app/Updating-the-RC-App.html) includes instructions for both OnBot Java and Blocks, but has no instructions for Android Studio. 

It is mentioned that the steps shown are not for Android Studio users, and that teams should ensure their projects are up to date with the main SDK repository. However, there are no actual instructions or resources given to accomplishing that. Certainly, some teams will have members skilled enough in Git and VCS to accomplish it on their own, but those aren't the students who are reading these guides. Aside from community resources, there is no easy way for a team to find help on this process.

With that being said, it is hard to give concise instructions for updating the SDK version given that each user's circumstances may vary. However, even a simple guide, such as using a couple very simple Git commands, or using the Github Desktop GUI, would go a long way to making Android Studio easier to use for more teams.

**Comment by uvidyadharan** [comment]
Thanks for the feedback. A guide to updating the RC for Android Studios users is certainly something that we would like to add.

**Comment by texasdiaz** [comment]
Craig added a guide a few months back, but I realize it might not be 100% clear that the guide exists. I changed some of the wording on the "Updating-the-RC-app.html" page to better clarify that the guide exists, and that users of Android Studio should check it out for its intended use. I'm hoping this helps out, please let me know if you feel it is still lacking. We agree that it's impossible to give concise instructions because of the different configurations and user circumstances, but I feel like the guide provides education and a quick-start that should help the vast majority of teams who "take it seriously."

#180 should resolve this issue.

**Comment by Lunerwalker2** [comment]
Sorry for leaving this dormant; linking to that guide is great! I wasn't fully aware of its existence before either.

As a side question, I've personally made my own team's repos both with forking it and also cloning the SDK, with my personal preference being towards cloning since that makes the project more isolated (although updating the SDK version requires some extra Git commands). For example, people accidentally submitting PRs to the official SDK repo is not as easy.

Is there a reason why the forking method is preferred here? I don't have any problems with it; both methods are similar amounts of steps and achieve basically the same outcome, but I was wondering the ethos behind that.

**Comment by texasdiaz** [comment]
The Forking method is vastly preferred because a clone is generally not sharable within a team - cloning makes a *local* copy of the repository, NOT your *team's own* copy. If there are multiple *remote* users (users who are not sitting at the single computer) who will collaborate with you on writing your team's code, you cannot do that from within a clone of a repository. Clones of a repository are just for *you*. Clones are beneficial if you're planning on contributing to the repository, but since teams ARE NOT ALLOWED to push changes back up to the FtcRobotController repository, this benefit is of no use. It's true that clones are specifically linked to the repository, whereas Forks are not, but we provide instructions on how to set the upstream remote so that you can sync from the FtcRobotController repository from a clone of *your* forked repository. There is no way to "save" a local repository, if someone deletes the local clone or the computer is lost or trashed, you lose all of your work (clones are only managed locally, not from GitHub or similar). The only real "backup" of your code is from a forked repository.

For FTC teams, each team should have their own forked repository owned by a GitHub account managed by the team. Each collaborator within the team should clone the team's forked repository using their own accounts, work on code, and commit/push back to the team's repository. When updating the team's repository with changes from the FtcRobotController, that should be managed from a clone of the team's repository and submitted back to the team's repository via a PR. In this way, multiple users can collaborate on code AND the result of that collaboration is actually stored/saved in the cloud. When the laptop is reformatted or the main programmer graduates, the code doesn't disappear.

**Comment by Lunerwalker2** [comment]
I may have spoke a bit weirdly regarding the cloning method. That method involves making a local clone (either through cloning the SDK repo directly or downloading as a ZIP) and then changing the "remote origin" URL to a repository of your creation. Example from my GitHub desktop of 1002's PowerPlay project.

![image](https://github.com/FIRST-Tech-Challenge/ftcdocs/assets/55162022/f310ccbd-6a11-4f40-b923-8df9012f4cd7)

rough process:
1. Clone the official SDK (download zip or git clone)
2. Create a repository on github
3. Change the remote origin to the URL of your newly created repository
4. Push to the new repository.

This leaves no connection back to the official SDK, except when you need to add it as a remote upstream location in order to merge from for SDK updates (in the same way used for forks). This is the method me and lots of other teams use instead of forking.

**Comment by texasdiaz** [comment]
Oh, I see. Yeah, that's one way to create a clean "copy" that guarantees that you don't accidentally push back to the FtcRobotController repo. But this is only a workaround to GitHub's inability to provide a reasonable solution.

For instance, it would be awesome if we could create a template repo that can be updated with changes, OR if we could specify (like Gitea does) that nobody (without administrator access) is allowed to submit PRs. But unfortunately GitHub is dumb like that.

One cool alternative that GitHub has come up with is called Detaching/Extracting a Fork. They've created a [fun little chatbot](https://support.github.com/contact?tags=rr-forks&subject=Detach%20Fork&flow=detach_fork) that can help you detach/extract a fork, so that it removes the fork from the repo network and puts it into a new one. This really should be a Git command, but alas I understand Git saying, "no, not my perfect little princess!" But, with this tool you can go ahead and create the fork like we say, and then use the Detach feature to "pluck" it from the network and keep your safety/sanity. But I wouldn't recommend this to a casual user - but you seem like you can handle it.
